services:
 
  flask:
    build:
      context: flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    volumes:
      - ./flask:/src
    ports:
      - 9091:9091
    restart: always


  nextjs:
    image: next
    build: ./nextjs
    volumes:
      - ./nextjs:/app
    ports:
      - 3000:3000
    restart: always
  

